DROP database IF EXISTS MovieWeb;
CREATE DATABASE IF NOT EXISTS MovieWeb;
USE MovieWeb;
create table FILMS (
    ID INT(5) PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL,
    ID_GEN INT(3),
    DIRECTOR VARCHAR(20)
);
create table ACTOR (
    ID_ACTOR INT(3) PRIMARY KEY,
    NAME VARCHAR(15)
);
CREATE TABLE MAIN_CHARACTER (
    ID_ACTOR INT(3),
    NAME_CH VARCHAR(15),
    ID_FILM INT(5),
    CONSTRAINT PRIMARY KEY (ID_ACTOR,ID_FILM)
);
CREATE TABLE GENDER (
    ID_GEN INT(3) PRIMARY KEY,
    DESCRIPTION VARCHAR(20)
);