create table FILMS ( # 1:1 with MAIN_CHARACTER
    INT(5) PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL,
    ID_GEN INT(3),
    DIRECTOR VARCHAR(20)
);

create table ACTOR ( # n:m with FILM
    ID_ACTOR INT(3) PRIMARY KEY,
    NAME VARCHAR(15)
);

CREATE TABLE MAIN_CHARACTER ( # 1:1 with ACTOR
    ID_ACTOR INT(3),
    NAME_CH VARCHAR(15),
    ID_FILM INT(5),
    CONSTRAINT PRIMARY KEY (ID_ACTOR,ID_FILM)
);

CREATE TABLE GENDER ( # 1:n with FILMS
    ID_GEN INT(3) PRIMARY KEY,
    DESCRIPTION VARCHAR(20)
);