DROP database IF EXISTS MovieWeb;

CREATE DATABASE IF NOT EXISTS MovieWeb;

USE MovieWeb; -- connend test

CREATE TABLE IF NOT EXISTS FILMS( -- connend test
    ID INT(5) PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL,
    ID_GEN INT(3),
    DIRECTOR VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS ACTOR(
    ID_ACTOR INT(3) PRIMARY KEY,
    NAME VARCHAR(15)
);
CREATE TABLE IF NOT EXISTS MAIN_CHAPTER( -- connend test
    ID_ACTOR INT(3),
    NAME_CH VARCHAR(15),
    ID_FILM INT(5),
    CONSTRAINT PRIMARY KEY (ID_ACTOR,ID_FILM)
);
CREATE TABLE IF NOT EXISTS GENRE( -- connend test
    ID_GEN INT(3) PRIMARY KEY,
    DESCRIPTION VARCHAR(20)
);
